### ISSUE TITLE
CMAKE, MAKE and Compiler versions

### ISSUE THREAD

**Issue by Hrishiaudivo** [nikisalli/Kicad-nikfemm#4]
Could you please specify the versions of CMAKE, MAKE and which C and C++ compilers are you using?

**Comment by nikisalli** [comment]
Hi, everything is already defined in the cmake files in the nikfemm repository github.com/nikisalli/nikfemm

for short, any compiler that supports c++20 should work and at least cmake > 3.5.0

**Comment by Hrishiaudivo** [comment]
I am using Mingw and it|s not working

**Comment by nikisalli** [comment]
what's the error?

**Comment by Hrishiaudivo** [comment]
C:\Users\kunchepuh\Documents\KiCad\8.0>cd nikfemm/python

C:\Users\kunchepuh\Documents\KiCad\8.0\nikfemm\python>pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing c:\users\kunchepuh\documents\kicad\8.0\nikfemm\python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: nikfemm
  Building wheel for nikfemm (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running bdist_wheel
      running build
      running build_ext
      CMake Error: CMake was unable to find a build program corresponding to "MinGW Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\kunchepuh\Documents\KiCad\8.0\nikfemm\python\setup.py", line 40, in <module>
          setup(
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\wheel\bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\command\build.py", line 132, in run
          self.run_command(cmd_name)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\cmd.py", line 319, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\dist.py", line 1217, in run_command
          super().run_command(command)
        File "C:\Program Files\KiCad\8.0\bin\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
        File "C:\Users\kunchepuh\Documents\KiCad\8.0\nikfemm\python\setup.py", line 13, in run
          self.build_cmake()
        File "C:\Users\kunchepuh\Documents\KiCad\8.0\nikfemm\python\setup.py", line 23, in build_cmake
          subprocess.check_call(['cmake', debug_flag, '-DNIKFEMM_USE_OPENCV=OFF', '-DNIKFEMM_BUILD_TESTS=OFF', '-G', 'MinGW Makefiles', '..'], cwd=build_dir)
        File "C:\Program Files\KiCad\8.0\bin\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '-DCMAKE_BUILD_TYPE=Release', '-DNIKFEMM_USE_OPENCV=OFF', '-DNIKFEMM_BUILD_TESTS=OFF', '-G', 'MinGW Makefiles', '..']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nikfemm
  Running setup.py clean for nikfemm
Failed to build nikfemm
ERROR: Could not build wheels for nikfemm, which is required to install pyproject.toml-based projects

**Comment by nikisalli** [comment]
hi, this is a problem with your installation, you need to install mingw-make.

google your error to find the steps to do it

**Comment by nikisalli** [comment]
I'm closing this as it is a problem with your environment
feel free to reopen the issue if you find a problem with the actual package
